# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-21 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_text',
            field=models.TextField(blank=True),
        ),
    ]
