# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-27 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0002_product_image_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.BooleanField(default=True),
        ),
    ]
