# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-23 14:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0001_initial'),
        ('apka', '0002_product_image_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Imię')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Nazwisko*')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('address', models.CharField(max_length=250, verbose_name='Adres zamieszkania')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Kod pocztowy')),
                ('city', models.CharField(max_length=100, verbose_name='Miasto')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('model_wysylki', models.CharField(choices=[('1', 'Kurier InPost  - pobranie'), ('2', 'Paczkomaty InPost - pobranie'), ('3', 'Poczta Polska - pobranie')], max_length=250, verbose_name='Sposób wysyłki')),
                ('paczkomat', models.CharField(blank=True, max_length=250, verbose_name='Nazwa Paczkomatu* np. WRO01L, Krakowska 6/7, 50-425 Wrocław')),
                ('nr_telefonu', models.CharField(max_length=11, verbose_name='Nr telefonu XXX-XXX-XXX')),
                ('uwaga', models.CharField(blank=True, max_length=250, verbose_name='Uwagi dla nadawcy*')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='coupons.Coupon')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='apka.Product')),
            ],
        ),
    ]
