# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-27 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='model_wysylki',
            field=models.CharField(max_length=250, verbose_name='Sposób wysyłki'),
        ),
        migrations.AlterField(
            model_name='order',
            name='nr_telefonu',
            field=models.CharField(max_length=11, verbose_name='Nr telefonu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paczkomat',
            field=models.CharField(blank=True, max_length=250, verbose_name='Nazwa Paczkomatu*'),
        ),
    ]
